### PR TITLE
hi,,, i saw no fri gam

### PR DESCRIPTION
**Pull request by kekmaster97**
so i ad

### CODE REVIEW

**Comment by wrathsoffire76** [comment]
You must add more FRII GAM

**Comment by 6100m** [comment]
lol lets troll luma with these xD

**Comment by 6100m** [comment]
btw new discord coming soon

**Comment by Cyuubi** [comment]
made a new discord https://discord.gg/VfPSsk

**Comment by kekmaster97** [comment]
what the FRICK!!!! i though you axep aney pr!!!!              jus tbe cause im a dog doen t mean you can discrimina te agina FEFOSHEEP

**Pull request closed without merging**
