### PR TITLE
Added another to the load!

### PR DESCRIPTION
**Pull request by 6100m**

### CODE REVIEW

**Comment by Jan200101** [comment]
what the hell are you even doing

you are just mindlessly making Pull Requests and adding files to it that conflic with the remote branch

**Comment by ihaveamac** [comment]
do you know what Quality Control means?

**Comment by 6100m** [comment]
You obviously don't. Now get the hell out of my fork.

**Comment by notrankin** [comment]
But isn't this open source? We can laugh at whatever we want.

**Comment by ihaveamac** [comment]
I wish you good luck in dealing with merge conflicts.

**Comment by 6100m** [comment]
@ihaveamac I didn't mean to get mad at you, seriously I'm a big fan of your work. It's just that I'm at my wits end with Hikari-chin.

**Comment by ihaveamac** [comment]
anyone that's a contributor to the Luma3DS repo would have told you that your PR was low quality. Hikari-chin is usually just the one that manages the issue tracker.

**Comment by 6100m** [comment]
All good? No hard feelings I hope.

**Pull request closed without merging**
